services:
  - type: web
    name: cryptocat-web
    env: python
    buildCommand: "pip install -r web/requirements.txt"
    startCommand: "gunicorn app:app -w 2 -b 0.0.0.0:$PORT"
    plan: starter

  - type: worker
    name: cryptocat-worker
    env: python
    buildCommand: "pip install -r worker/requirements.txt"
    startCommand: "python main.py"
    plan: starter
